### ISSUE TITLE
Add support for other color sensitive variants

### ISSUE THREAD

**Issue by garth** [javifm86/tailwindcss-prefers-dark-mode#1]
For example the following variants often require color overrides when in dark-mode

```
      'dark:odd',
      'dark:even',
      'dark:disabled',
```

**Comment by javifm86** [comment]
> 
> 
> For example the following variants often require color overrides when in dark-mode
> 
> ```
>       'dark:odd',
>       'dark:even',
>       'dark:disabled',
> ```

Added odd, even and disabled. Just run `npm update` and bring new version. Thanks for the issue.
